Adding linterns to the feature branch
Huemac-Alfredo/Forms pull request #2
Opened 2020-06-25 00:21 UTC by JbirdL86

In this pull request we are trying to fix the error flags on the linters.

2020-06-30 20:42 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello team 👋. Hands down this is the most detailed project I have ever seen. You guys gave me a hard time figuring out which was the original page. Perfect 💯 !

You made your clone in such a way that it cannot be touched 👌! Now would you please make a killer README, because right now it just contains the name of the project.

Apply this small change and request another code review.

Happy coding 👨‍💻

2020-06-30 23:04 UTC, JbirdL86 reviewed
Thank you very much for your positive feedback! We are very exited about your comments, it really makes us see our progress from 0 to a whole other level! Thank you!!!!

I think we are ready now @tirthajyoti-ghosh .

2020-06-30 23:06 UTC, JbirdL86 commented
@tirthajyoti-ghosh i'm not sure how to proceed to resubmit the pull request. Can you help me?

2020-06-30 23:56 UTC, elmejdki approved these changes
# status Approved :heavy_check_mark: 
## Great job guys your clone looks exactly as the original :100: 

now you can merge to master you project is approved :+1: 

## Happy Coding :tophat:

2020-06-30 23:58 UTC, elmejdki approved these changes

2020-06-30 23:58 UTC, elmejdki commented on README.md
> +
Please remove all of this empty titles

2020-06-30 23:58 UTC, elmejdki commented on README.md
> +![screenshot](./assets/images/formsScreenShot.png)
and fix the image is not showing up I proved your project cause you showed a great job but you need to fix this before you go to another project

2020-07-01 14:41 UTC, JbirdL86 commented
Thank you guys! We are exited about your comments!

2020-07-01 14:41 UTC, merged